// Every .jpg/.png under public/ has a resized .webp twin generated by
// scripts/optimize-images.mjs, so local image URLs are rewritten to .webp here.
const toWebp = (path) => path.replace(/\.(jpe?g|png)$/i, '.webp');

export const asset = (path) => toWebp(`/eotcdskm-export/assets/${path.replace(/^\//, '')}`);

export const localAsset = (path) => new URL(path, import.meta.url).href;

// Grid/card-sized variant (520px wide) of any local image.
export function thumbAsset(value = '') {
  const resolved = resolveAsset(value);
  if (!resolved || /^(https?:|data:)/.test(resolved)) return resolved;
  return resolved.replace(/(?<!\.thumb)\.webp$/i, '.thumb.webp');
}

export function resolveAsset(value = '') {
  if (!value) return value;
  if (value.startsWith('http://') || value.startsWith('https://') || value.startsWith('data:')) return value;
  if (value.startsWith('/eotcdskm-export/assets/')) return toWebp(value);
  if (value.startsWith('/static/')) return toWebp(`/eotcdskm-export/assets${value}`);
  if (value.startsWith('static/')) return toWebp(`/eotcdskm-export/assets/${value}`);
  if (value.startsWith('/favicon.ico')) return '/eotcdskm-export/assets/favicon.ico';
  if (value.startsWith('/manifest.json')) return '/eotcdskm-export/assets/manifest.json';
  if (value.startsWith('/asset-manifest.json')) return '/eotcdskm-export/assets/asset-manifest.json';
  return toWebp(value);
}
